import type { Composition } from '../../backend/src/providers/composition/schema.js';
import { expandComposition } from '../../backend/src/providers/composition/schema.js';

/** Structural observations, never a subjective music score or proof of commercial readiness. */
export function evaluateComposition(score: Composition, duration: number) {
  const events = expandComposition(score,duration); const melodic=score.parts.filter(part=>part.instrument!=='drums');
  const used=new Set(melodic.map(part=>part.patternId)); const patterns=score.patterns.filter(pattern=>used.has(pattern.id));
  const fingerprints=patterns.map(pattern=>JSON.stringify(pattern.notes.map(note=>[note.beat,note.duration,note.pitch-pattern.notes[0]!.pitch])));
  const melodicEvents=events.filter(event=>event.instrument!=='drums'); const drumEvents=events.filter(event=>event.instrument==='drums');
  const pcs=new Set(melodicEvents.map(event=>event.pitch%12));
  const tonalFits=[];
  for (let tonic=0;tonic<12;tonic++) for (const [mode,intervals] of [['major',[0,2,4,5,7,9,11]],['natural minor',[0,2,3,5,7,8,10]]] as const) {
    const scale=new Set(intervals.map(interval=>(interval+tonic)%12)); const total=melodicEvents.reduce((sum,event)=>sum+event.gate,0);
    tonalFits.push({tonicPitchClass:tonic,mode,durationCoverage:total?melodicEvents.filter(event=>scale.has(event.pitch%12)).reduce((sum,event)=>sum+event.gate,0)/total:0});
  }
  tonalFits.sort((a,b)=>b.durationCoverage-a.durationCoverage);
  const sections=score.sections.map(section=>{
    const start=section.startBar*240/score.bpm, end=Math.min(duration,(section.startBar+section.bars)*240/score.bpm);
    const notes=events.filter(event=>event.start>=start&&event.start<end);
    const activeParts=score.parts.filter(part=>part.startBar<section.startBar+section.bars&&part.startBar+score.patterns.find(pattern=>pattern.id===part.patternId)!.bars*part.repeats>section.startBar);
    return { name:section.name,startSeconds:start,endSeconds:end,instruments:[...new Set(activeParts.map(part=>part.instrument))],melodicPatternIds:[...new Set(activeParts.filter(part=>part.instrument!=='drums').map(part=>part.patternId))].sort(),noteOnsets:notes.length,onsetsPerSecond:notes.length/(end-start),meanAttackStrength:notes.length?notes.reduce((sum,event)=>sum+event.velocity*event.gain,0)/notes.length:0 };
  });
  const quarterKickPositions=new Set(drumEvents.filter(event=>event.pitch===36&&Math.abs(event.start*score.bpm/60-Math.round(event.start*score.bpm/60))<0.04).map(event=>Math.round(event.start*score.bpm/60)));
  const bass=melodicEvents.filter(event=>event.instrument==='bass').map(event=>event.pitch).sort((a,b)=>a-b);
  const lowAndHigh = (values:number[])=>values.length?{minimum:Math.min(...values),maximum:Math.max(...values)}:null;
  const motifsSharedWithChorus = sections.filter(section=>section.name!=='chorus'&&section.melodicPatternIds.some(id=>sections.find(row=>row.name==='chorus')!.melodicPatternIds.includes(id))).map(section=>section.name);
  const longestPatternRepetitionSeconds=Math.max(...melodic.map(part=>part.repeats*score.patterns.find(pattern=>pattern.id===part.patternId)!.bars*240/score.bpm));
  const observations:string[]=[];
  if (patterns.every(pattern=>pattern.bars<=2)) observations.push('All authored melodic motifs are at most two bars; longer phrases are generated by repetition.');
  if (longestPatternRepetitionSeconds>=20) observations.push('At least one melodic part repeats unchanged for 20 seconds or longer.');
  if (new Set(fingerprints).size<patterns.length) observations.push('Some melodic patterns share identical rhythm/duration/interval contours despite different IDs.');
  if (bass.length&&bass[Math.floor(bass.length/2)]!>=55) observations.push('Median bass pitch is high for a conventional low bass role; inspect register by listening.');
  if (['House','Techno'].includes(score.genre)&&quarterKickPositions.size/Math.floor(duration*score.bpm/60)<0.5) observations.push('Quarter-note kick coverage is below half of the full timeline; inspect the main groove and intentional breaks.');
  if (drumEvents.length===0 && ['Hip-hop','Trap','R&B / Soul','Pop','Rock','Funk','Jazz','House','Techno','Drum & Bass','Latin','Reggae / Dub'].includes(score.genre)) observations.push('No notated drum part despite percussion in the benchmark brief; rhythmic genre adherence needs review.');
  if (score.genre==='Ambient'&&drumEvents.length>0) observations.push('Ambient includes percussion; inspect whether it fits the requested texture.');
  return { method:'symbolic-v1; heuristic observations, no perceptual rating',subjectiveQuality:'unassessed',sunoComparison:'unassessed',commercialReadiness:'unassessed',bpm:score.bpm,timeSignature:'4/4',patternCount:score.patterns.length,melodicPatternCount:patterns.length,authoredMelodicNotes:patterns.reduce((sum,pattern)=>sum+pattern.notes.length,0),uniqueIntervalRhythmMotifs:new Set(fingerprints).size,expandedNoteOnsets:events.length,pitchClassCount:pcs.size,melodicPitchRange:lowAndHigh(melodicEvents.map(event=>event.pitch)),bassPitchRange:lowAndHigh(bass),drumOnsets:drumEvents.length,quarterKickTimelineCoverage:quarterKickPositions.size/Math.floor(duration*score.bpm/60),longestPatternRepetitionSeconds,tonalFitHeuristic:tonalFits[0],motifsSharedWithChorus,sections,observations };
}
